bio_exam:
    resource: "@BioExamBundle/Controller/"
    type:     annotation
    prefix:   /

bio_score:
    resource: "@BioScoreBundle/Controller/"
    type:     annotation
    prefix:   /

find_score:
    path:     /scores/find
    defaults: { _controller: BioScoreBundle:Default:find }

bio_user:
    resource: "@BioUserBundle/Controller/"
    type:     annotation
    prefix:   /

bio_public:
    resource: "@BioPublicBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /check

logout:
    pattern:   /logout

bio_folder:
    resource: "@BioFolderBundle/Controller/"
    type:     annotation
    prefix:   /

bio_clicker:
    resource: "@BioClickerBundle/Controller/"
    type:     annotation
    prefix:   /

register_clicker:
    path:     /clicker/register
    defaults: { _controller: BioClickerBundle:Default:register }

bio_student:
    resource: "@BioStudentBundle/Controller/"
    type:     annotation
    prefix:   /

bio_style:
    resource: "@BioStyleBundle/Controller/"
    type:     annotation
    prefix:   /

bio_info:
    resource: "@BioInfoBundle/Controller/"
    type:     annotation
    prefix:   /