bio_student:
    resource: "@BioStudentBundle/Controller/"
    type:     annotation
    prefix:   /

bio_style:
        resource: "@BioStyleBundle/Controller/"
        type:     annotation
        prefix:   /
