bio_clicker:
    resource: "@BioClickerBundle/Controller/"
    type:     annotation
    prefix:   /

bio_student:
    resource: "@BioStudentBundle/Controller/"
    type:     annotation
    prefix:   /

bio_style:
        resource: "@BioStyleBundle/Controller/"
        type:     annotation
        prefix:   /

bio_info:
    resource: "@BioInfoBundle/Controller/"
    type:     annotation
    prefix:   /