security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check 
            logout:
                path: logout
                target: main_page
            access_denied_handler: kernel.listener.access_denied.handler
            switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/user/delete, roles: ROLE_SUPER_ADMIN}

    providers:
        main:
            entity: { class: Bio\UserBundle\Entity\User, property: username}

    encoders:
        Bio\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN: [ROLE_USER]