security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|js|images|bundles)
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                use_referer: true 
            logout:
                path: logout
                target: main_page
            access_denied_handler: kernel.listener.access_denied.handler
            switch_user: true

    access_control:
        # - { path: ^/user/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY } #
        - { path: ^/admin/user/, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/, roles: ROLE_USER } #
        - { path: ^/trip/promo$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(exam|trip|switch|clicker|scores), roles: ROLE_STUDENT }
        - { path: ^/user/change, roles: ROLE_USER }

    providers:
        chain_provider:
            chain:
                providers: [students, admins]#, default] #
        admins:
            entity: { class: Bio\UserBundle\Entity\User, property: username}
        students:
            entity: { class: Bio\StudentBundle\Entity\Student, property: sid}
        # default: #
        #     memory: #
        #         users: #
        #             username: { password: password, roles: 'ROLE_USER' } #

    encoders:
        Bio\UserBundle\Entity\User: sha512
        Bio\StudentBundle\Entity\Student: sha512
        # Symfony\Component\Security\Core\User\User: plaintext #

    role_hierarchy:
        ROLE_SETUP: [ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_STUDENT]
        ROLE_STUDENT: [ROLE_USER]