security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check 
            logout:
                path: logout
                target: main_page
            switch_user: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]