services:
    bio.database:
        class: Bio\DataBundle\Objects\DatabaseService
        arguments: ["@doctrine"]
    bio.database.connection.setter:
        class: Bio\DataBundle\Objects\DatabaseConnectionSetter
        arguments: ["@service_container", "%database_user%", "%database_password%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100}
    bio.twig.extension:
        class: Bio\DataBundle\Twig\BioExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }