services:
    bio.database:
        class: Bio\DataBundle\Objects\DatabaseService
        arguments: ["@doctrine"]
    bio.twig.extension:
        class: Bio\DataBundle\Twig\BioExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }