<?php

namespace Bio\DataBundle\Objects;

use Doctrine\DBAL\Driver\PDOMySql\Driver;
use Doctrine\DBAL\Driver\PDOConnection;

class CustomDriver extends Driver {

	private $conn;

	public function connect(array $params, $username = null, $password = null, array $driverOptions = Array()) {
		
		$route = array();

		// taken from autogenerated appDevUrlMatcher.php in the cache
		if (preg_match('#^/(?P<year>[^/]++)/(?P<quarter>[^/]++)/(?P<number>[^/]++)/#', $_SERVER['PATH_INFO'], $route)) {
			$params['dbname'] = $route['number'].'-'.$route['quarter'].'-'.$route['year'];
		}

		$conn = new PDOConnection(
			$this->constructPdoDsn($params),
			$username,
			$password,
			$driverOptions
		);
		return $conn;
	}

	// shameless stolen from the parent class
    private function constructPdoDsn(array $params)
    {
        $dsn = 'mysql:';
        if (isset($params['host']) && $params['host'] != '') {
            $dsn .= 'host=' . $params['host'] . ';';
        }
        if (isset($params['port'])) {
            $dsn .= 'port=' . $params['port'] . ';';
        }
        if (isset($params['dbname'])) {
            $dsn .= 'dbname=' . $params['dbname'] . ';';
        }
        if (isset($params['unix_socket'])) {
            $dsn .= 'unix_socket=' . $params['unix_socket'] . ';';
        }
        if (isset($params['charset'])) {
            $dsn .= 'charset=' . $params['charset'] . ';';
        }

        return $dsn;
    }
	
}