'Course Info':
    'Course Info':
        route: info_instruct
    'Edit Info':
        route: edit_info
    Announcements:
        route: view
        vars:
            entityName: announcement
    Instructors:
        route: view
        vars:
            entityName: person
    Hours:
        route: view
        vars:
            entityName: hours
    "Course Sections":
        route: view
        vars:
            entityName: courseSection
    "Lab Sections":
        route: view
        vars:
            entityName: section