'Course Info':
    'Course Info':
        route: info_instruct
    'Edit Info':
        route: edit_info
    Announcements:
        route: view
        vars:
            entityName: announcement
    Instructors:
        route: view
        vars:
            entityName: person
    Hours:
        route: view
        vars:
            entityName: hours
    Sections:
        route: view
        vars:
            entityName: section