Exams:
    Exams:
        route: exam_instruct
    'Manage Exams':
        route: manage_exams
    'Manage Questions':
        route: manage_questions
    'Practice Exams':
        route: exam_entrance
