Clickers:
    Manage:
        route: manage_clickers
    Clickers:
        route: clicker_instruct
    Download:
        route: download_list
    Clear:
        route: clear_list
    Register:
        route: register_clicker