"Trips":
    "Trips":
        route: trip_instruct
    "Manage Trips":
        route: manage_trips
    "Manage Evaluations":
        route: trip_evals
    "Field Trips":
        route: trip_entrance
    "My Trips":
        route: tour_guide_entrance
    "Promo Page":
        route: promo
