"Trips":
    "Trips":
        route: main_page
    "Manage Trips":
        route: manage_trips
    "Manage Evaluations":
        route: trip_evals
    "Field Trips":
        route: trip_entrance
    "Tour Guides":
        route: tour_guide_entrance
